Repository sourabhjagtap95/AwesomePythonScripts, pull requests merged in 2022-10, with the labels that each got.

#63 Double Linked List PR4
  double_linked_list.py
Labels: hacktoberfest

#62 Circular Linked List PR3
  circular_linked_list.py
Labels: hacktoberfest

#61 Validate filenames PR2
  validate_filenames.py
Labels: hacktoberfest, hacktoberfest-accepted

#60 Create build directory PR1
  build_directory.py
Labels: hacktoberfest, hacktoberfest-accepted

#65 Create parser_video.py
  parser_video.py
Labels: hacktoberfest-accepted
